---
- name: Test Connectivity to managed hosts 
  hosts: managed

  tasks:
   - name: Ping all managed hosts 
     ansible.builtin.ping:
   - name: Print Message
     ansible.builtin.debug:
       msg: Hello World, All hosts pinged successfully !!

